# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.2.0
        with:
          key: ${{ secrets.TWITTER_BOTS }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: copy files and build docker (haiku)
        run: |
          scp -r ./src/ ubuntu@ec2-3-249-242-117.eu-west-1.compute.amazonaws.com:.
          scp -r ./docker/ ubuntu@ec2-3-249-242-117.eu-west-1.compute.amazonaws.com:.
          scp requirements.txt ubuntu@ec2-3-249-242-117.eu-west-1.compute.amazonaws.com:.
          ssh -tt ubuntu@ec2-3-249-242-117.eu-west-1.compute.amazonaws.com \
          "docker build -f docker/Haiku.Dockerfile -t haiku-bot . && \
          docker run -it haiku-bot"

      - name: copy files and build docker (ye)
        run: |
          scp -r ./src/ ubuntu@ec2-3-249-85-209.eu-west-1.compute.amazonaws.com:.
          scp -r ./docker/ ubuntu@ec2-3-249-85-209.eu-west-1.compute.amazonaws.com:.
          scp requirements.txt ./ ubuntu@ec2-3-249-85-209.eu-west-1.compute.amazonaws.com:.
          ssh -tt ubuntu@ec2-3-249-85-209.eu-west-1.compute.amazonaws.com \
          "docker build -f docker/Ye.Dockerfile -t ye-bot . && \
          docker run -it ye-bot"
